title: Zachary Newton
email: zacharyrnewton@gmail.com
description: "This is my description"
baseurl: "/zn"
url: "https://zacharyrnewton.github.io"
instagram_link: https://www.instagram.com/zacharyrnewton/
youtube_link:  https://www.youtube.com/zacharyrnewton

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
collections:
  projects:
    output: true
