title: Zachary Newton
email: zacharyrnewton@gmail.com
phone: "+1-754-368-1567"
description: "I am Zachary. I am a Design Director, UX/UI Designer, and Deverloper. Here are some products/projects I have worked on."
keywords:
  - "Design Director"
  - "UX Design"
  - "UI Design"
  - "Development"
  - "Education"
baseurl: ""
url: "https://zacharynewton.me"
twitterHandle: "_zacharyrnewton"

#Variables
instagram_link: https://www.instagram.com/zacharyrnewton/
youtube_link:  https://www.youtube.com/zacharyrnewton
skills:
  - "Design Director"
  - "UX Designer"
  - "UI Designer"
  - "Developer"
  - "YouTuber"
  #- "Editor"


# Build settings
permalink: pretty
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
collections:
  projects:
    output: true
  books:
    output: false
